name: CI Workflow

on: [push, workflow_dispatch]

jobs:
  build and test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure Cmake
        run: | 
          cmake ${{github.workspace}}/build
          make Tests
          ./Tests