name: CI Workflow

on: [push, workflow_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure Cmake
        run: |
          git clone git@github.com:catchorg/Catch2.git
          mkdir build
          cd build
          cmake ..
          make Tests
          ./Tests